[package]
name = "slime-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
slime-core = { path = "../slime-core" }
ratatui = "0.26.1"
crossterm = "0.27.0"
anyhow = "1.0.82"
tokio = { version = "1.37.0", features = ["full"] }
